Private Sub Suche_Open()
Label1.Font.Size = 30
End Sub

Private Sub Label1_Click()

End Sub

Private Sub Suchen_Click()
    Dim rng As Range
    Dim x As String
    x = TextBox1
    Set rng = ActiveSheet.Range("A1:Z100000").Find(x)
    If rng Is Nothing Then
        MsgBox "nix gefunden ... gib was sinnvolles ein! :) "
        Exit Sub
    End If
    rng.Select
    
   
    Select Case rng.Column
    Case Is = 2
        y = 0
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 3
        y = -1
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 4
        y = -2
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 5
           y = -3
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 6
           y = -4
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 7
           y = -5
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 8
           y = -6
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 9
           y = -7
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 10
           y = -8
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 11
           y = -9
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 12
           y = -10
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 13
           y = -11
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 14
           y = -12
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 15
           y = -13
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 16
           y = -14
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 17
           y = -15
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 18
           y = -16
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 19
           y = -17
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 20
           y = -18
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 21
           y = -19
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 22
           y = -20
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    Case Is = 23
           y = -21
        Me.TextBox_FT.Text = rng.Offset(0, (y - 1)).Value
        Me.TextBox_Lieferant.Text = rng.Offset(0, (y)).Value
        Me.TextBox_EAN.Text = rng.Offset(, (y + 1)).Value
        Me.TextBox_Artikelnummer.Text = rng.Offset(, (y + 2)).Value
        Me.TextBox_CEE_Nr.Text = rng.Offset(, (y + 3)).Value
        Me.TextBox_Artikelbezeichnung.Text = rng.Offset(, (y + 4)).Value
        Me.TextBox_Lieferantenartikelnummer.Text = rng.Offset(, (y + 5)).Value
        Me.TextBox_Arbeitstitel.Text = rng.Offset(, (y + 6)).Value
        Me.TextBox_Gerät_1.Text = rng.Offset(, (y + 7)).Value
        Me.TextBox_Gerät_2.Text = rng.Offset(, (y + 8)).Value
        Me.TextBox_Gerät_3.Text = rng.Offset(, (y + 9)).Value
        Me.TextBox_Gerät_4.Text = rng.Offset(, (y + 10)).Value
        Me.TextBox_Zubehör_1.Text = rng.Offset(, (y + 11)).Value
        Me.TextBox_Zubehör_2.Text = rng.Offset(, (y + 12)).Value
        Me.TextBox_Zubehör_3.Text = rng.Offset(, (y + 13)).Value
        Me.TextBox_Zubehör_4.Text = rng.Offset(, (y + 14)).Value
        Me.TextBox_Zubehör_5.Text = rng.Offset(, (y + 15)).Value
        Me.TextBox_Zubehör_6.Text = rng.Offset(, (y + 16)).Value
        Me.TextBox_Zubehör_7.Text = rng.Offset(, (y + 17)).Value
        Me.TextBox_Zubehör_8.Text = rng.Offset(, (y + 18)).Value
        Me.TextBox_Zubehör_9.Text = rng.Offset(, (y + 19)).Value
        Me.TextBox_Zubehör_10.Text = rng.Offset(, (y + 20)).Value
        Me.TextBox_Zubehör_11.Text = rng.Offset(, (y + 21)).Value
    End Select
   
    End Sub
    
    
  
